### ISSUE TITLE
###BETSET_MATCH_GOALS_HOME### / ###BETSET_MATCH_GOALS_GUEST###

### ISSUE THREAD

**Issue by iresults-tma** [digedag/t3sportsbet#10]
After Update from version 1.0.0 to 1.0.1 the markers `###BETSET_MATCH_GOALS_HOME###` and `###BETSET_MATCH_GOALS_GUEST###` are no longer replaced. Even if I use the standard template. Has something changed here?

**Comment by digedag** [comment]
Yes, the used models changed. I currently refactor all used classes in T3sports to PSR-4. I think this will be completed within June. After that task is done, this bug will be fixed to.

**Comment by digedag** [comment]
Fixed in current master
