### ISSUE TITLE
Missing trailing backslash in Service.yaml

### ISSUE THREAD

**Issue by cundd** [digedag/t3sportsbet#15]
The latest tagged version has a bug which you later fixed:
https://github.com/digedag/t3sportsbet/commit/4f5ae23eda732e7a666d1904196a42b19daf6d0c#diff-d2a9a6effbda1d2c980f54b0f322f984996372c98b3af0577b8ec747d467735c

This crashed my TYPO3 v11 instance.

We are planing to test the master branch with v12 support soon, but I wanted to let you know that there is a problem with the latest release.

Anyway: Thank you for providing this extension(s).

**Comment by digedag** [comment]
Thank you for reporting the problem. :+1:  I have just released version 1.3.0 into the TER. This should also fix the error in TYPO3 11. If there are any problems, please let me know. I don't have much time at the moment to do intensive testing myself.

**Comment by cundd** [comment]
Look good to me. Thank you!
