### ISSUE TITLE
Add support for TYPO3 9.5/10.4

### ISSUE THREAD

**Issue by digedag** [digedag/t3sportsbet#3]

**Comment by iresults-tma** [comment]
Will there be support for TYPO3 9.5 / 10.4? I was able to install the extension. However, the rendering of the templates does not work. 

`Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::substituteMarkerArrayCached()`

**Comment by digedag** [comment]
I fixed that call. Could you try it again?

**Comment by iresults-tma** [comment]
It works. Thanks for the quick fix!

**Comment by iresults-tma** [comment]
> I fixed that call. Could you try it again?

It works. Thanks for the quick fix!

**Comment by iresults-tma** [comment]
I have discovered another error on the high score view.

`Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::getSubpart()`

**Comment by digedag** [comment]
It*s fixed too. Thank's for testing!

**Comment by digedag** [comment]
Still a lot to do, but it should run in TYPO3 11.5 and PHP 8 now.
